cd "D:/Dokumente/CodeProjects/ValheimPressurePlate"
cp "./PressurePlate/bin/Debug/net472/PressurePlate.dll" "C:/Users/maxsc/AppData/Roaming/r2modmanPlus-local/Valheim/profiles/Default/BepInEx/plugins/PressurePlate.dll"
cp "./PressurePlate/bin/Debug/net472/PressurePlate.dll" "./UnityAssets/Assets/Assemblies/PressurePlate.dll"
cp "./PressurePlate/bin/Debug/net472/PressurePlate.dll" "D:/Nextcloud/Dokumente/Valheim"
cp "./UnityAssets/AssetBundles/StandaloneWindows/pressure_plate" "./PressurePlate/pressure_plate"